### ISSUE TITLE
the code is not compiled by swift3

### ISSUE THREAD

**Issue by AndriiRybak** [00buggy00/SwiftOpenGLTutorials#1]
```
    if let vss = source.cString(using: String.Encoding.utf8) {
        var vssptr = UnsafePointer<GLchar>(vss)
        //  This takes our string an puts it into the GPU's shader source code
        glShaderSource(vs, 1, &vssptr, nil)  // Cannot pass immutable value as inout argument: implicit conversion from 'UnsafePointer<GLchar>' to 'UnsafePointer<GLchar>?' requires a temporary
```

....
}

**Comment by BuggusMageevers** [comment]
You need to remove the `vss` local variable from the `if let` closure so that `vss` remains an optional.  Then when you pass in `vssptr` to `glShaderSource()`, you'll be passing in the expected type:  `UnsafePointer<UnsafePointer<GLchar>?>!`.

```
let vss = source.cString(using: String.Encoding.utf8)
var vssptr = UnsafePointer<GLchar>(vss)
//  This takes our string an puts it into the GPU's shader source code
glShaderSource(vs, 1, &vssptr, nil)
....
```

I haven't attempted to run this with UTF8 encoding, but that should get rid of your error.  Let me know if something else comes up.

**Comment by AndriiRybak** [comment]
I have do next:
1. i change 
`let vss = source.cString(using: String.Encoding.utf8)`
to 
`let vss = source.cString(using: String.Encoding.ascii)`
2. i change 
`var fssptr = getPointer(fss)` 
to 
`var fssptr = UnsafePointer<GLchar>(fss)`
3. i perform your suggestion but i pay price for that: i remove "if" flow control statement
4. i comment parts of code that generate logs of shaders (pieces of code in "if compiled <= 0", "if linked <= 0" cause got next error:

> Cannot invoke initializer for type 'UnsafeMutablePointer<CChar>' with an argument list of type '(UnsafeMutableRawPointer!)'

in next strings: 
`let cLog = UnsafeMutablePointer<CChar>(malloc(Int(logLength)))`

After that program work correctly

**Comment by BuggusMageevers** [comment]
Ah yes, that one a result of one Swift 3's new features:  reworked unsafe pointers.  You can find more information [here](https://github.com/apple/swift-evolution/blob/master/proposals/0107-unsaferawpointer.md).  The point being that a new type was introduced to ensure better type safety.  At the same time, the way in which we work with `Unsafe[Mutable]Pointer`'s has changed.  You can see how I incorporated the changes in each of the files on this repository (I have updated all of them to work with Swift 3), but for your case shown here, the specific workaround is as follows:  the error your receiving is because you are not properly creating an `UnsafeMutablePointer`.  `UnsafeMutablePointer` has some new methods to use since Swift 3 (you can see a type definition [here](https://developer.apple.com/reference/swift/unsafemutablepointer) in the Swift 3 documentation).

```
//  Used GLchar in stead of CChar because that is what OpenGL uses, but CChar works, too.
let cLog = UnsafeMutablePointer<GLchar>.allocate(capacity: Int(logLength))

//  Pass in the pointer to your log
glGetShaderInfoLog(vs, GLsizei(logLength), &logLength, cLog)

//  Now when we want to print it, we need to turn it back into a Swift String.
//  Use the cString initializer on String.
Swift.print(" log: \n\t\(String(cString: cLog))")

//  Now that we are done with the UnsafeMutablePointer, we need to clean up the memory.
//  First deinitialize:  take what you put into that reserved memory out.
cLog.deinitialize()

//  Then free the memory with deallocate so that something else can use it.
//  Notice that you need to specify how much memory to deallocate just like when you reserved it
//    with allocate(capacity:)
cLog.deallocate(capacity: Int(logLength))
```

You can probably use free(), but I feel that the design of `UnsafeMutablePointer` begs one to use it's deinitialize(), deallocate(_:) methods increase clarity when an unsafe type has been released from memory.  I haven't tested free() to see if it still deinitializes and deallocates as expected, but I know that according to the documentation on Swift Evolution's GitHub, that these new methods are what is expected for handling the new pointer types.

I hope that helps.  There is a portion of code that requires the new `Unsafe[Mutable]RawPointer` type as well.  Let me know if you need some explanation with that one as well, it can be a bit of mind bender, lol, at least it was for me at first.
